export const en = {
    translation:{
        title:"Elitar Shin",
        home:"Home",
        projects:"Projects",
        about:"About Us",
        mainTitle:"Elitar-Shin",
        quote:"Where quality meets reliability in construction",
        innovativeEngineering:"Innovative Engineering",
        smartConstruction:"Smart Construction",
        sustainableSolutions:"Sustainable Solutions",
        advnacedMaterials:"Advnaced Materials",
        precisionBuilding:"Precision Building",
        cuttingEdgeTechnology:"Cutting-Edge Technology",
        projects:"Projects",
        projectsQoute:"We build Elitar structures that set new standards in quality and technology!",
        bgresidence:"Bagrevand Residence",
        townhouses:"TownHouses",
        blocks:"Blocks, Concrete Manufacturing",
        katlavan:"Katlavan",
        seemore:"See More",
        bgstories:"Bagrevand Residence",
        recentStories:"RECENT STORIES",
        dfprj:"FROM DIFERENT PROJECTS",
        builds:"Three high-rise buildings",
        bgabout:"Our organization is currently implementing an apartment complex construction project in the Bagrevand Residence district. The project includes 3 buildings. the first 9-story, the second 16-story, and the third 15-story, as well as 2-story underground parking. The buildings are still under construction and full completion is expected in December 2025.",
        twnstories:"TownHouses",
        katlavanstories:"Construction services",
        apartments:"Apartment complex construction",
        twnbuilds:"Construction of townhouses complex",
        earthworks:"Digging foundations",
        ourProjects:"Our Projects",
        aboutUs:"About Us",
        bgMap:"Bagrevand Residence",
        twnMap:"TownHouses",
        office:"Our Office",
        address:"6/6 Bagrevand Street, 1st Building",
        bulding1:"Building 1",
        bulding2:"Building 2",
        bulding3:"Building 3",
        allPosts:"All Posts",
        news:"News",
        build1Info:"The first building consists of 3 buildings: 9, 15 and 14 floors. Each building is designed for the comfort of residents, incorporating the best solutions for a modern residential environment. A 2-story underground parking lot is planned under the building.",
        build2Info:"The second building, consisting of two 16-story buildings, is designed to become a high-class residential complex using innovative architectural solutions. The 4-story underground parking lot under the building will provide spacious and comfortable parking conditions. One of the significant features is that on the 2nd floor it is planned to create modern and practical office spaces, which will combine all the necessary conditions for business activities, creating an ideal balance between residential and working environments.",
        build3Info:"The third building includes one 10-story building. It is distinguished by its compact structure and optimal use of residential space. A 2-story underground parking lot is planned under the building to meet the parking needs of residents.",
        twn:"TownHouses",
        twnInfo:"This project, which was launched in 2020 and successfully completed in 2022, represents a complex of modern townhouses, which stands out for its modern and innovative solutions. The design of the buildings emphasizes the combination of minimalist style and functionality: large windows, green roofs and high-quality construction materials that ensure durability and comfort. The townhouses are designed to provide a modern living environment, offering both aesthetic and functional solutions. The design features of the complex include not only modern architectural approaches, but also enclosed courtyard areas that ensure the comfort and safety of residents. These townhouses embody high-quality construction standards, integrating natural and technological elements, which allows you to create a comfortable and practical living environment, fully meeting modern requirements.",
        katlavan:"Katlavan",
        katlavanInfo:"We specialize in earthworks, using the latest technologies that ensure high efficiency and excellent quality. Our team consists of experienced specialists who provide high-level services, paying attention to every detail. We are currently engaged in the excavation of the foundation of the second building of the Bagrevand Residence complex. We carry out these works in accordance with all technical requirements to ensure safety and high quality standards. Our goal is to complete the works on time, ensuring the fulfillment of customer expectations and creating trust in our company. We also coordinate the works using modern software, which allows us to ensure a high level of communication and efficiency during the implementation of projects. Our staff is dedicated to each project and strives to always exceed customer expectations.",
        block:"Blocks Manufacturing",
        blockInfo:"Elitar Shin company has been producing pumice blocks since 2018, becoming a reliable partner in the construction industry. The company has provided pumice blocks for many large construction projects, standing out for the high durability and thermal insulation properties of its products. Today, Elitar Shin pumice blocks are used in the construction of the Bagrevand Residence district, supporting the rapid and efficient implementation of projects.",
        concrete:"Concrete",
        concreteInfo:"Elitar Shin company has been engaged in concrete production since 2018, providing high-quality and durable concrete for various construction projects. The company has collaborated in a number of important projects, providing concrete for the construction of various buildings and structures. Currently, Elitar Shin` also supplies concrete to the construction projects of the Bagrevand Residence district, continuing to contribute to the modern architectural developments of the city.",
        pomp:"Concrete Pump",
        pompInfo:"We provide high-quality concrete pumping services using 18-meter and 42-meter concrete mixers. Our equipment ensures reliable and efficient concrete placement even in the most difficult to reach areas, which allows you to increase the speed and quality of construction work. Our team ensures that the work is carried out accurately and on time, meeting the highest technical and safety requirements.",
        bulding1news:"1 Building Posts",
        bulding2news:"2 Building Posts",
        bulding3news:"3 Building Posts",


        
    }
} 